# version: '3.8'
# services:
#   git-config:
#     image: ubuntu:latest
#     secrets:
#     - git_token
#     # Add 'sleep infinity' to keep the container running
#     command: >
#       bash -c "apt-get update && apt-get install -y git &&
#       git config --global user.name 'My Git User' &&
#       git config --global user.token $$(cat /run/secrets/git_token) &&
#       sleep infinity"  # <--- Keeps the container running
# secrets:
#   git_token:
#     external: true
services:
  # The service defined in your original question, corrected to stay running
  git-config:
    image: ubuntu:latest
    secrets:
      - git_token
    # Command ensures setup runs, then keeps the container alive (sleep infinity)
    command: >
      bash -c "apt-get update && apt-get install -y git &&
      git config --global user.name 'My Git User' &&
      git config --global user.token $$(cat /run/secrets/git_token) &&
      sleep infinity"

  # The service that was failing to pull (imagem-teste-seguro)
  app:
    # 1. Use 'build' to compile the image from a local Dockerfile
    build: .
    # 2. Use 'image' to assign the resulting name, resolving the "pull access denied" error
    image: imagem-teste-seguro:latest
    ports:
      - "80:80" # Example port mapping

secrets:
  git_token:
    external: true
