version: '3.8'

services:
  git-config:
    image: ubuntu:latest
    secrets:
      - git_token
    command: >
      bash -c "
        apt-get update && apt-get install -y git &&
        git config --global user.name 'My Git User' &&
        # ESCAPE O $ COM $$. Assim, o Swarm/Compose não tenta interpolar a variável.
        git config --global user.token $$(cat /run/secrets/git_token)
      "
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  git_token:
    external: true